version: 1  # Set at "definitions.go"

# [ INFRASTRUCTURE ]
# --------------------------------------------------------------------------------------------------

infrastructure:

  # PostgreSQL
  postgresql:
    connection: ""
    connection-timeout: 0  # Seconds

  # Valkey
  valkey:
    connection: ""
    username: ""
    password: ""
    connection-timeout: 0  # Seconds

  # Ollama
  ollama:
    connection: ""
    connection-timeout: 0  # Seconds
    operation-timeout: 0  # Seconds



# [ PROVIDER ]
# --------------------------------------------------------------------------------------------------

provider:

  # AI server
  ai:
    connection: ""
    request-timeout: 0  # Seconds

  # SMS server
  sms:
    kavenegar:
      apikey: ""
      otp-template: ""
